version: '3.3'

services:
  login-fronted:
    image: login-frontend
    container_name: login-frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
     - "3000:3000"
  web:
    container_name: appName
    restart: always
    build: .
    ports:
      - "3200:3200"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/backend/app
  mongo:
    container_name: mongoDataBase
    image: mongo
    
    ports:
      - "27017:27017"